### ISSUE TITLE
请求Github Permission：FumaSim GUI

### ISSUE THREAD

**Issue by SeanMWX** [RShock/fumaSim#1]
吧主你好，我是昨天找你问Github link的人
感觉贴吧里面有部分大佬不怎么会用Java，所以写了一个GUI这样大佬们也能用
不知能不能有点帮助
基于的版本是7df93d2db634fedfa4337ac2b4effc55fa154a75

git push需要permission 请求一个permission

**Comment by RShock** [comment]
等我研究下怎么开

**Comment by SeanMWX** [comment]
Okay的

**Comment by SeanMWX** [comment]
可可，看见了，GUI代码在sean_zouzhe给branch里面，
写得不太好，部分代码hardcode，比如CharaPanel里面的ImportedCharaPanel里面的characters类
大致的GUI长这个样子
[fumasim GUI](https://ibb.co/kqD4LJt)
但是这只是在ide里面运行的，我看看怎么样打包出来。

**Comment by SeanMWX** [comment]
那我就把这个issue close了？
